### ISSUE TITLE
Getting PolicySignatureException

### ISSUE THREAD

**Issue by Mar-ch** [filestack/filestack-java#36]
Hello,
I have a problem getting image uploading to work. I tried replicating the following iOS code, which works fine:

```
    let filestack = Filestack(apiKey: signature.filepickerKey)
    let security = FSSecurity(policy: signature.policy, signature: signature.uploadSignature
    let storeOptions = FSStoreOptions()
    storeOptions.access = FSAccessPublic
    storeOptions.container = 'dev'
    storeOptions.security = security
    storeOptions.path = "/users/" + "\(userId)" + "/avatar"
    filestack.store(imageData, with: storeOptions, progress: { (progress) in },
    completionHandler: { (blob, error) in if (error == nil) {
    }
```

The code I'm trying to get to work on Android looks like this:

```
FilestackClient client = new FilestackClient(signature.filepickerKey(), Security.fromExisting(signature.policy(), signature.signature()));
        String path = "/users/" + userId + "/avatar";
        StorageOptions options = new StorageOptions.Builder()
                .access("public")
                .container("dev")
                .path(path)
                .build();
        client.uploadAsync(getRealPathFromURI(context, uri), "image/jpeg", options).subscribe(new SingleObserver<FileLink>() {
            @Override
            public void onSubscribe(@NonNull Disposable d) {
                Timber.d("onSubscribe()");
            }
            @Override
            public void onSuccess(@NonNull FileLink fileLink) {
                Timber.d("onSuccess()");
            }
            @Override
            public void onError(@NonNull Throwable e) {
                Timber.d("onError()");
            }
        });
```

The problem I have is receiving an exception: `com.filestack.errors.PolicySignatureException`
Don't know why could this be the case? The signatures provided from out endpoint work perfectly fine on iOS? Maybe I'm missing something?

**Comment by Mar-ch** [comment]
I managed to find a workaround for this issue. It seems like setting the storage container makes the `PolicySignatureException` to be thrown for me.

It is a bit strange then that setting this on iOS doesn't cause this. A slight inconsistency. Maybe it's colliding with the container that is sent via policy? They do have the same name though.

**Comment by shawnmaten** [comment]
Can you send me the policy JSON you're using? The exceptions mostly just wrap response codes from the backend, so if you're getting a `PolicySignatureException` the backend is sending a 403 for some reason.

**Comment by shawnmaten** [comment]
Closing this since it's been sitting for awhile.
